### ISSUE TITLE
Ginform example, multiple files

### ISSUE THREAD

**Issue by dhartford** [mazrean/formstream#20]
Do you have support / quick example if using multi-part formdata with Gin where using formstream to 'stream' receive multiple files in a single multipart/formdata post (i.e. file1/file2/file3/file4) to save each file independently?

usecase: uploading 2x 20mb files and 2x 2mb files in a single post, where the two larger ones would be better streamed-handled, and could be in any order (may not be the first file* field).

thanks!

**Comment by mazrean** [comment]
Hello! Thank you for bringing up this issue. I appreciate your patience and interest in improving our library.

To achieve the functionality you're asking for, I've prepared a solution that you can follow. Please take a look at this Gist: https://gist.github.com/mazrean/9f873209e7b382b3d4693f0ff50b6b8a. This example should guide you through implementing the desired feature using our library.

Thank you for using our library!
